### ISSUE TITLE
/Components/log/ problems

### ISSUE THREAD

**Issue by erha527** [LLLLLyra/planning_controlling_simulation#1]
Hello, when i run launch.launch, i met a problem:

> E20230529 20:14:14.583253 25610 simple_pid_lat_lon_controller.cc:18] Fail to open file:/Components/log/speed_log__2023-05-29_201414.csv

what should  i do to solve it because the repository does not have this file?
Thanks!

**Comment by LLLLLyra** [comment]
Hi,

Thanks for the message. 

To solve the problem, there are only a few steps.
- As mentioned in **Quick Start** of `README`, update all the paths listed in the `Components/common/config/log_path_conf.h` and `Components/scripts/obstacles_service.py` to make sure  all of them exist in `${your_workspace_folder}/src/`, i.e. `${your_workspace_folder}/src/Components/common/config/control_conf.pb.lattice.txt`.
- Create a log directory under `${your_workspace_folder}/src/Components` using `mkdir log`.

If there are any questions else, feel free to propose them.

Kind Regards,
Lyra

**Comment by erha527** [comment]
The problem is solved!Thank you very very very much!
