### ISSUE TITLE
关于可视化

### ISSUE THREAD

**Issue by nkuwenjian** [LLLLLyra/planning_controlling_simulation#3]
您好，我看到您展示的动图效果，应该是用matplotlib进行可视化的。请问您是把车辆的轨迹记录下来离线可视化么，还是可以边跑程序边可视化？

**Comment by sysyushuo** [comment]
目前主要为离线可视化，在线可视化需要修改相关可视化代码

**Comment by LLLLLyra** [comment]
> 您好，我看到您展示的动图效果，应该是用matplotlib进行可视化的。请问您是把车辆的轨迹记录下来离线可视化么，还是可以边跑程序边可视化？

Hi, 

感谢您的提问。

车辆轨迹既可以通过程序运行时保存的log信息进行离线可视化，也可以在线。

对于离线可视化，您只需要读入相关log文件绘制想看的信息即可，这是一件比较简单的事情，因此该仓库暂未提供样例。

对于在线可视化播放，相关信息通过`src/Components/nodes/pc_node/display.cc`发布，可自行配置rviz进行可视化（一些plugins可能并不适配），也可以另起`src/Components/scripts/display.py`节点利用matplotlib可视化。当采用matplotlib可视化时，相关数据在每一帧都将被更新，因此可直接使用`animation.FuncAnimation`绘制动图。

**Comment by xyf27323** [comment]
请问障碍物的信息是怎么配置的呀，是slot.json这个文件吗，这些坐标应该怎么理解呀

**Comment by LLLLLyra** [comment]
> 请问障碍物的信息是怎么配置的呀，是slot.json这个文件吗，这些坐标应该怎么理解呀

Hi, 

详细请见`slot.json`中新增注释.
