### ISSUE TITLE
Is SimplePIDLatLonController or OpenLoopController applicable to vehicle control in Carla simulator?

### ISSUE THREAD

**Issue by hbc2020** [LLLLLyra/planning_controlling_simulation#4]
Dear Author,
Thanks for your work, I want to know whether SimplePIDLatLonController or OpenLoopController could be applied to the vehicle in Carla simulator to complete the parking process, since only speed and steer angle are generated as commands by these controllers, while throttle, brake as well as steer commands are needed by Carla simulator for vehicle control.

**Comment by LLLLLyra** [comment]
Hi,

Thanks for your message. 

Basically, the answer is **YES**. But there is still some supplementary work to be done.

- You should output acceleration command and write your own calibration table, and then convert them to throttle / brake command.
- Pay attention to signs of steer command of the controllers and CARLA.

**Comment by hbc2020** [comment]
Thanks for your reply!
This issue is solved.
