### ISSUE TITLE
安装了说明中的dependencies，但编译时出现大量的“c_float’ was not declared in this scope”，请问什么原因？谢谢

### ISSUE THREAD

**Issue by Tavifeng** [LLLLLyra/planning_controlling_simulation#5]

**Comment by Tavifeng** [comment]
I asked for chatGPT.It said that code should " #include cfloat" .But I don't find any code relevantly. How to solve it? Thanks!

**Comment by LLLLLyra** [comment]
Hi, 

Seems you have installed `OSQP` of the latest version. Lots of apis have been changed in `OSQP`. I suggest you keeping it as same as in Apollo. 

Kind regards,
LLLLLyra
